spring:
  datasource:
    url: jdbc:mysql://qiuqian.xyz:3306/library?useUnicode=true&characterEncoding=UTF-8
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8181